import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="
                  min-h-screen 
                  flex 
                  flex-col 
                  justify-center 
                  items-center
        "
      >
        <header>
          <h1>React & Next /c MOURINHO💕</h1>
          <nav className="flex justify-center items-center gap-4">
            <Link href="/">Home</Link>
            <Link href="/route">Route</Link>
            <Link href="/caracteristicas">Caracteristicas</Link>
            <Link href="/tecnologias">Tecnologias</Link>
            <Link href="/projetos">Projetos</Link>
          </nav>
        </header>
        <main className="bg-pink-500 w-[80vw] min-h-[40vh] p-5">
          {children}
        </main>
        <footer>DIW</footer>
      </body>
    </html>
  );
}
